import Head from 'next/head';
import { useState, useEffect } from 'react';
import Navbar from "./Navbar";
import Footer from "./Footer";
import { Box } from "@chakra-ui/react";

function Layout({children}){
    const layoutPaddingX = ["0.75rem", "1rem", "2rem", "5rem"];

    // To control responsiveness in real time
    const [width, setWidth] = useState(900);
    useEffect(() => {
        setWidth(window.innerWidth);
        const handleResizeWindow = () => setWidth(window.innerWidth);
        window.addEventListener("resize", handleResizeWindow);
        return () => {
            window.removeEventListener("resize", handleResizeWindow);
        }
    }, []);

    return (
        <>
            <Head>
                <title>ATX DAO</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Navbar 
                    paddingX={layoutPaddingX} 
                    width={width}
                />

                <Box mb="5rem">
                    {children}
                </Box>
            </main>

            <footer>
                <Footer 
                    paddingX={layoutPaddingX} 
                    width={width}
                />
            </footer>

        </>
    )
}

export default Layout;