name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  lint-and-build:
    name: Test
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_ALCHEMY_ID: ${{ secrets.NEXT_PUBLIC_ALCHEMY_ID }}
      NEXT_PUBLIC_ETHERSCAN_API_KEY: ${{ secrets.NEXT_PUBLIC_ETHERSCAN_API_KEY }}
      NEXT_PUBLIC_INFURA_ID: ${{ secrets.NEXT_PUBLIC_INFURA_ID }}
      NEXT_PRIVATE_EVENTBRITE_KEY: ${{ secrets.NEXT_PRIVATE_EVENTBRITE_KEY }}
      NEXT_PRIVATE_EVENTBRITE_ORGID: ${{ secrets.NEXT_PRIVATE_EVENTBRITE_ORGID }}
      NEXT_SESSION_PRIVATE_KEY: ${{ secrets.NEXT_SESSION_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install Deps
        run: yarn install
      - name: Typecheck
        run: yarn type-check
      - name: Lint js
        run: yarn lint
      - name: Build
        run: yarn build
