name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  lint-and-build:
    name: Test
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_ALCHEMY_ID: ${{ secrets.NEXT_PUBLIC_ALCHEMY_ID }}
      NEXT_PUBLIC_ETHERSCAN_API_KEY: ${{ secrets.NEXT_PUBLIC_ETHERSCAN_API_KEY }}
      NEXT_PUBLIC_INFURA_ID: ${{ secrets.NEXT_PUBLIC_INFURA_ID }}
      NEXT_PRIVATE_EVENTBRITE_KEY: ${{ secrets.NEXT_PRIVATE_EVENTBRITE_KEY }}
      NEXT_PRIVATE_EVENTBRITE_ORGID: ${{ secrets.NEXT_PRIVATE_EVENTBRITE_ORGID }}
      NEXT_SESSION_PRIVATE_KEY: ${{ secrets.NEXT_SESSION_PRIVATE_KEY }}
      NEXT_WALLETCONNECT_PROJECT_ID: ${{ secrets.NEXT_WALLETCONNECT_PROJECT_ID }}
      NEXT_PUBLIC_ALCHEMY_ID_SEPOLIA: ${{ secrets.NEXT_PUBLIC_ALCHEMY_ID_SEPOLIA }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for cache hit or miss
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Deps
        run: yarn install --frozen-lockfile
      - name: Typecheck
        run: yarn type-check
      - name: Lint js
        run: yarn lint
      - name: Build
        run: yarn build
